# Generated by Django 4.1.7 on 2023-06-19 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project_Api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='graphics',
            name='color',
            field=models.CharField(default=False, max_length=1000),
        ),
    ]
