# Generated by Django 4.1.7 on 2023-06-19 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Project_Api', '0002_graphics_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='graphics',
            old_name='relationTemplateGraphics_id',
            new_name='relationTemplateGraphics',
        ),
    ]
