# Generated by Django 4.1.7 on 2023-06-19 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project_Api', '0003_rename_relationtemplategraphics_id_graphics_relationtemplategraphics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devices',
            name='location',
            field=models.CharField(max_length=1000),
        ),
    ]
