# Generated by Django 4.1.7 on 2023-06-21 01:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Project_Api', '0004_alter_devices_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='datossensores',
            name='relationTemplatePin',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='pin', to='Project_Api.template'),
        ),
    ]
