# Generated by Django 4.1.7 on 2023-06-21 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project_Api', '0005_datossensores_relationtemplatepin'),
    ]

    operations = [
        migrations.AddField(
            model_name='devices',
            name='template',
            field=models.CharField(default=False, max_length=1000),
        ),
    ]
