# Generated by Django 4.1.7 on 2023-06-26 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project_Api', '0006_devices_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='graphics',
            name='ports',
            field=models.CharField(default=False, max_length=1000),
        ),
    ]
