# Generated by Django 4.1.7 on 2023-06-28 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project_Api', '0007_graphics_ports'),
    ]

    operations = [
        migrations.AddField(
            model_name='graphics',
            name='size_decrease',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='graphics',
            name='size_increase',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
